# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["master"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      # Checkout repo
      - name: Checkout
        uses: actions/checkout@v3
      # Setup Ruby
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1.117.0
        with:
          ruby-version: ".tool-versions" # Use ruby version in `.tool-versions` file
          bundler-cache: true # Auto run `bundle install`
      # Generate website
      - name: Generate Website
        run: "bundle exec ruby ./bin/generate"
      # Upload only the ./www directory
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          # Upload entire repository
          path: "./www"
      # Deploy the site
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
